In [39]:
!pip install numpy pandas scikit-learn

Requirement already satisfied: numpy in c:\ml_env\venv\lib\site-packages (2.4.1)
Requirement already satisfied: pandas in c:\ml_env\venv\lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in c:\ml_env\venv\lib\site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\ml_env\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\ml_env\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\ml_env\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.10.0 in c:\ml_env\venv\lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\ml_env\venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\ml_env\venv\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\ml_env\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [40]:
import numpy as np
import pandas as pd
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [41]:
df = pd.read_csv('breast-cancer.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [42]:
df.drop(columns=['id'], inplace=True)

In [43]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [44]:
df.shape

(569, 31)

In [45]:
X = df.iloc[:, 1:]
y = df.iloc[:, 0]

encoder = LabelEncoder()
y = encoder.fit_transform(y)

x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
)

In [46]:
df.dtypes

diagnosis                   object
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_worst          float64
concavity_worst            float64
concave points_worst       float64
symmetry_worst             float64
fractal_dimension_worst    float64
dtype: object

In [47]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [48]:
x_train

array([[-0.74676236, -1.02135339, -0.7351201 , ..., -0.76928528,
        -1.74691371, -0.52832279],
       [-0.07151101, -0.72182437, -0.13882454, ..., -0.88043434,
        -0.85537211, -0.69589891],
       [-0.1730732 , -1.53450001, -0.25140068, ..., -1.38300837,
        -1.00908618, -1.18741994],
       ...,
       [ 1.03743837,  0.39502415,  1.28846599, ...,  1.23500277,
         0.5733597 ,  1.90153089],
       [ 0.10965399, -1.23961485,  0.0735983 , ..., -0.10930014,
        -0.46056967, -0.32392263],
       [-0.45854532,  1.09624713, -0.31982152, ...,  1.60449832,
         2.3871857 ,  6.58192113]], shape=(455, 30))

In [49]:
y_train

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1])

In [50]:
y_train.shape

(455,)

In [51]:
import torch

In [52]:
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [53]:
x_train_tensor.shape

torch.Size([455, 30])

In [54]:
x_train_tensor

tensor([[-0.7468, -1.0214, -0.7351,  ..., -0.7693, -1.7469, -0.5283],
        [-0.0715, -0.7218, -0.1388,  ..., -0.8804, -0.8554, -0.6959],
        [-0.1731, -1.5345, -0.2514,  ..., -1.3830, -1.0091, -1.1874],
        ...,
        [ 1.0374,  0.3950,  1.2885,  ...,  1.2350,  0.5734,  1.9015],
        [ 0.1097, -1.2396,  0.0736,  ..., -0.1093, -0.4606, -0.3239],
        [-0.4585,  1.0962, -0.3198,  ...,  1.6045,  2.3872,  6.5819]])

In [55]:
class MYsimpleNN(nn.Module):
    
    def __init__(self,num_features):
        super().__init__()
        self.Linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,features):
        out = self.Linear(features)
        out = self.sigmoid(out)
        return out
    def binarycrossentropyloss(self,y_pred,y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        loss = -torch.mean(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred))
        return loss

In [56]:
learning_rate = 0.1
epochs = 50

In [57]:
# creating model
model = MYsimpleNN(x_train_tensor.shape[1])

# define loop
for epoch in range(epochs):
    # forward pass
    y_pred = model(x_train_tensor)
    # print(y_pred)
    # loss calculation
    loss = model.binarycrossentropyloss(y_pred,y_train_tensor)
    # back propagation
    loss.backward()
    # update weights and bias  
    with torch.no_grad():
        model.Linear.weight -= learning_rate * model.Linear.weight.grad
        model.Linear.bias -= learning_rate * model.Linear.bias.grad
    # zero gradients
    model.Linear.weight.grad.zero_()
    model.Linear.bias.grad.zero_()

    
    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item()}")

Epoch 1/50, Loss: 0.7098553776741028
Epoch 2/50, Loss: 0.7040046453475952
Epoch 3/50, Loss: 0.6999412775039673
Epoch 4/50, Loss: 0.6968955397605896
Epoch 5/50, Loss: 0.6944524645805359
Epoch 6/50, Loss: 0.6923897862434387
Epoch 7/50, Loss: 0.6905858516693115
Epoch 8/50, Loss: 0.6889705061912537
Epoch 9/50, Loss: 0.6875014305114746
Epoch 10/50, Loss: 0.6861505508422852
Epoch 11/50, Loss: 0.6848987340927124
Epoch 12/50, Loss: 0.6837320327758789
Epoch 13/50, Loss: 0.6826399564743042

Epoch 14/50, Loss: 0.6816143989562988
Epoch 15/50, Loss: 0.6806485652923584
Epoch 16/50, Loss: 0.6797372698783875
Epoch 17/50, Loss: 0.6788759827613831
Epoch 18/50, Loss: 0.67806077003479
Epoch 19/50, Loss: 0.6772883534431458
Epoch 20/50, Loss: 0.6765559911727905
Epoch 21/50, Loss: 0.6758610606193542
Epoch 22/50, Loss: 0.6752011179924011
Epoch 23/50, Loss: 0.6745743155479431
Epoch 24/50, Loss: 0.6739786267280579
Epoch 25/50, Loss: 0.6734123229980469
Epoch 26/50, Loss: 0.6728737354278564
Epoch 27/50, Loss: 0.6723614931106567
Epoch 28/50, Loss: 0.6718741059303284
Epoch 29/50, Loss: 0.6714102029800415
Epoch 30/50, Loss: 0.6709687113761902
Epoch 31/50, Loss: 0.6705483794212341
Epoch 32/50, Loss: 0.6701480746269226
Epoch 33/50, Loss: 0.6697669625282288
Epoch 34/50, Loss: 0.6694037318229675
Epoch 35/50, Loss: 0.6690578460693359
Epoch 36/50, Loss: 0.6687282919883728
Epoch 37/50, Loss: 0.6684141159057617
Epoch 38/50, Loss: 0.6681147217750549
Epoch 39/50, Loss: 0.6678293943405151
Epoch 40/50, Loss: 0.6675573587417603
Epoch 41/50, Loss: 0.667297899723053
Epoch 42/50, Loss: 0.6670504808425903
Epoch 43/50, Loss: 0.666814386844635
Epoch 44/50, Loss: 0.6665893197059631
Epoch 45/50, Loss: 0.6663745045661926
Epoch 46/50, Loss: 0.6661695241928101
Epoch 47/50, Loss: 0.6659740209579468
Epoch 48/50, Loss: 0.6657873392105103
Epoch 49/50, Loss: 0.6656090617179871
Epoch 50/50, Loss: 0.6654389500617981

In [59]:
model.Linear.weight

Parameter containing:
tensor([[-0.0177, -0.0588,  0.0508, -0.1446,  0.0678, -0.0435, -0.1234,  0.0500,
          0.0310, -0.0491, -0.0775,  0.0851, -0.0829,  0.1191,  0.0020, -0.0168,
          0.0147,  0.1047,  0.0348, -0.1182, -0.0456, -0.0133,  0.0837,  0.0989,
         -0.0848,  0.0190,  0.0482,  0.0196, -0.0748,  0.1407]],
       requires_grad=True)

In [60]:
model.Linear.bias

Parameter containing:
tensor([-0.3627], requires_grad=True)

In [61]:
with torch.no_grad():
    y_test_pred = model.forward(x_test_tensor)
    y_test_pred_labels = (y_test_pred > 0.5).float()
    accuracy = (y_test_pred_labels.squeeze() == y_test_tensor).float().mean()
    print(f"Test Accuracy: {accuracy.item() * 100:.2f}%")

Test Accuracy: 60.53%