In [58]:
!pip install numpy pandas scikit-learn

Requirement already satisfied: numpy in c:\ml_env\venv\lib\site-packages (2.4.1)
Requirement already satisfied: pandas in c:\ml_env\venv\lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in c:\ml_env\venv\lib\site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\ml_env\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\ml_env\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\ml_env\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.10.0 in c:\ml_env\venv\lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\ml_env\venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\ml_env\venv\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\ml_env\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [59]:
import numpy as np
import pandas as pd
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [60]:
df = pd.read_csv('breast-cancer.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [61]:
df.drop(columns=['id'], inplace=True)

In [62]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [63]:
df.shape

(569, 31)

In [64]:
X = df.iloc[:, 1:]
y = df.iloc[:, 0]

encoder = LabelEncoder()
y = encoder.fit_transform(y)

x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
)

In [65]:
df.dtypes

diagnosis                   object
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_worst          float64
concavity_worst            float64
concave points_worst       float64
symmetry_worst             float64
fractal_dimension_worst    float64
dtype: object

In [66]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [67]:
x_train

array([[-1.49675482, -0.60645523, -1.47905076, ..., -1.74542521,
        -0.7130686 ,  0.24301882],
       [-0.36452062,  0.67877831, -0.40284475, ..., -0.31727384,
        -0.09491637, -0.19708703],
       [ 2.58108373,  0.5806166 ,  2.46079907, ...,  1.84523295,
         1.12850992,  0.42060539],
       ...,
       [-0.13448295,  0.53495999, -0.1815003 , ..., -0.79817102,
        -0.71145883, -0.7723131 ],
       [ 0.15166148, -0.86898073,  0.04309921, ..., -0.8557195 ,
        -0.57623803, -1.50527135],
       [-0.97327885, -0.12477801, -0.90900743, ..., -0.53231538,
         0.08376826, -0.46181236]], shape=(455, 30))

In [68]:
y_train

array([0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [69]:
y_train.shape

(455,)

In [70]:
import torch

In [71]:
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [72]:
x_train_tensor.shape

torch.Size([455, 30])

In [73]:
x_train_tensor

tensor([[-1.4968, -0.6065, -1.4791,  ..., -1.7454, -0.7131,  0.2430],
        [-0.3645,  0.6788, -0.4028,  ..., -0.3173, -0.0949, -0.1971],
        [ 2.5811,  0.5806,  2.4608,  ...,  1.8452,  1.1285,  0.4206],
        ...,
        [-0.1345,  0.5350, -0.1815,  ..., -0.7982, -0.7115, -0.7723],
        [ 0.1517, -0.8690,  0.0431,  ..., -0.8557, -0.5762, -1.5053],
        [-0.9733, -0.1248, -0.9090,  ..., -0.5323,  0.0838, -0.4618]])

In [84]:
class MYsimpleNN(nn.Module):
    
    def __init__(self,num_features):
        super().__init__()
        self.Linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,features):
        out = self.Linear(features)
        out = self.sigmoid(out)
        return out
    
    binarycrossentropyloss = nn.BCELoss()

In [95]:
learning_rate = 0.1
epochs = 50

In [96]:
# creating model
model = MYsimpleNN(x_train_tensor.shape[1])

# optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):
    # forward pass
    y_pred = model(x_train_tensor)
    # print(y_pred)
    # loss calculation
    loss = model.binarycrossentropyloss(y_pred,y_train_tensor.view(-1,1))

    
    optimizer.zero_grad()

    # back propagation
    loss.backward()

    # update weights and bias  
    # with torch.no_grad():
    #     model.Linear.weight -= learning_rate * model.Linear.weight.grad
    #     model.Linear.bias -= learning_rate * model.Linear.bias.grad
    # # zero gradients
    # model.Linear.weight.grad.zero_()
    # model.Linear.bias.grad.zero_()

    # parameters update using optimizer
    optimizer.step()




    
    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item()}")

Epoch 1/50, Loss: 0.5633618831634521
Epoch 2/50, Loss: 0.29626306891441345
Epoch 3/50, Loss: 0.20243090391159058
Epoch 4/50, Loss: 0.15108807384967804
Epoch 5/50, Loss: 0.12177372723817825
Epoch 6/50, Loss: 0.10574650764465332
Epoch 7/50, Loss: 0.09650621563196182
Epoch 8/50, Loss: 0.09075955301523209
Epoch 9/50, Loss: 0.08691179752349854
Epoch 10/50, Loss: 0.08412321656942368
Epoch 11/50, Loss: 0.08192027360200882
Epoch 12/50, Loss: 0.08004190027713776
Epoch 13/50, Loss: 0.07836847752332687
Epoch 14/50, Loss: 0.07687000930309296
Epoch 15/50, Loss: 0.07555706799030304
Epoch 16/50, Loss: 0.07444335520267487
Epoch 17/50, Loss: 0.07352811098098755
Epoch 18/50, Loss: 0.07279413193464279
Epoch 19/50, Loss: 0.0722125992178917
Epoch 20/50, Loss: 0.07174915075302124
Epoch 21/50, Loss: 0.0713692158460617
Epoch 22/50, Loss: 0.07104209810495377
Epoch 23/50, Loss: 0.07074367254972458
Epoch 24/50, Loss: 0.07045762985944748
Epoch 25/50, Loss: 0.07017555832862854
Epoch 26/50, Loss: 0.06989610195159912
Epoch 27/50, Loss: 0.06962306797504425
Epoch 28/50, Loss: 0.06936319172382355
Epoch 29/50, Loss: 0.06912340223789215
Epoch 30/50, Loss: 0.06890830397605896
Epoch 31/50, Loss: 0.06871825456619263
Epoch 32/50, Loss: 0.06854868680238724
Epoch 33/50, Loss: 0.06839091330766678
Epoch 34/50, Loss: 0.06823445111513138
Epoch 35/50, Loss: 0.06806971877813339
Epoch 36/50, Loss: 0.06789061427116394
Epoch 37/50, Loss: 0.06769570708274841
Epoch 38/50, Loss: 0.06748819351196289
Epoch 39/50, Loss: 0.06727427244186401
Epoch 40/50, Loss: 0.06706120073795319
Epoch 41/50, Loss: 0.06685511767864227
Epoch 42/50, Loss: 0.06665962189435959
Epoch 43/50, Loss: 0.06647525727748871
Epoch 44/50, Loss: 0.06629998981952667
Epoch 45/50, Loss: 0.06613016128540039
Epoch 46/50, Loss: 0.06596154719591141
Epoch 47/50, Loss: 0.06579048186540604
Epoch 48/50, Loss: 0.0656144842505455
Epoch 49/50, Loss: 0.0654325783252716
Epoch 50/50, Loss: 0.06524526327848434

In [97]:
model.Linear.weight

Parameter containing:
tensor([[ 0.8320,  0.9510,  0.8468,  0.8309,  0.7362,  0.1064,  0.7376,  1.0025,
         -0.1532, -1.1158,  1.1643, -0.3455,  1.0945,  0.8969,  0.3026, -0.6356,
         -0.0687,  0.2851, -0.9577, -1.1375,  1.1057,  1.3892,  0.9054,  0.8771,
          1.1005,  0.3861,  0.8814,  0.9513,  1.1607,  0.1712]],
       requires_grad=True)

In [98]:
model.Linear.bias

Parameter containing:
tensor([-0.8924], requires_grad=True)

In [99]:
with torch.no_grad():
    y_test_pred = model.forward(x_test_tensor)
    y_test_pred_labels = (y_test_pred > 0.5).float()
    accuracy = (y_test_pred_labels.squeeze() == y_test_tensor).float().mean()
    print(f"Test Accuracy: {accuracy.item() * 100:.4f}%")

Test Accuracy: 99.1228%